name: dispatch

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Select log level"
        required: true
        type: choice
        default: warning
        options:
          - info
          - warning
          - debug
      environment:
        description: "Select environment"
        type: environment
      matrix:
        required: true
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(inputs.matrix) }}
    steps:
      - name: Log matrix info
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Using version: ${{ matrix.version }}"
      - name: Log inputs
        run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
