name: Test Secrets Access

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: TestEnvironment  # ðŸ”¹ to jest kluczowe â€” nazwa jak na GitHubie
    steps:
      - name: Show CLI_SECRET1
        run: echo "CLI_SECRET1: ${{ secrets.CLI_SECRET1 }}"

      - name: Save CLI_SECRET2
        run: echo "CLI_SECRET2: ${{ secrets.CLI_SECRET2 }}" > CLI_SECRET2.txt

      - uses: actions/upload-artifact@v4
        with:
          name: CLI_SECRET2
          path: CLI_SECRET2.txt

      - name: Save UI_SECRET
        run: echo "UI_SECRET: ${{ secrets.UI_SECRET }}" > UI_SECRET.txt

      - uses: actions/upload-artifact@v4
        with:
          name: UI_SECRET
          path: UI_SECRET.txt

      - name: Save ORG_SECRET
        run: echo "ORG_SECRET: ${{ secrets.ORG_SECRET }}" > ORG_SECRET.txt

      - uses: actions/upload-artifact@v4
        with:
          name: ORG_SECRET
          path: ORG_SECRET.txt

      - name: Save ENV_SECRET1
        run: echo "ENV_SECRET1: ${{ secrets.ENV_SECRET1 }}" > ENV_SECRET1.txt

      - uses: actions/upload-artifact@v4
        with:
          name: ENV_SECRET1
          path: ENV_SECRET1.txt
