# This is a basic workflow to help you get started with Actions

name: passing job values

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  pass_in_one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: echo "COLOR=Green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          COLOR: ${{ steps.color-selector.outputs.COLOR }}
        run: echo "The selected color is $COLOR"
        
  producer:
    runs-on: ubuntu-latest
    outputs:
      OUTPUT_JOB: ${{ steps.sentence_maker.outputs.MESSAGE }}
    steps:
      - name: Make a sentence
        id: sentence_maker
        run: |
          echo "MESSAGE=Example message" >> "$GITHUB_OUTPUT"

  consumer:
    runs-on: ubuntu-latest
    needs: [producer]
    steps:
      - name: Print the message
        run: |
          echo "From needs.producer.outputs: ${{ needs.producer.outputs.OUTPUT_JOB }}"

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - name: Calculate sum
        shell: bash
        run: |
          expr 3 + 7 > sum_result.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sum_result
          path: sum_result.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sum_result

      - name: Multiply result
        shell: bash
        run: |
          value=$(cat sum_result.txt)
          echo $(expr $value \* 9) 
